services:
  onlyflix:
    build: .
    container_name: onlyflix
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - LOCAL_PATH=/media
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
      - PUBLIC_URL=${PUBLIC_URL:-https://onlyflix.atrasado.online}
    volumes:
      - /caminho/para/seus/videos:/media:ro
      - ./.env:/app/.env
    restart: unless-stopped
