services:
  onlyflix:
    build: .
    container_name: onlyflix
    network_mode: "host"
    volumes:
      - ./token.json:/app/token.json
      - ./.env:/app/.env
      - ./downloads:/app/downloads
      - ./download_history.json:/app/download_history.json
      - ./catalog.json:/app/catalog.json
    restart: unless-stopped
